insert into bi_gameop.gameop_wide_dws(timeline_date, dim_type, business, pid, game_code, is_a, game_server, view, click,
                                      reg_num, login_new_num, new_num, new_arr, active_arr, valid_new, create_role_arr,
                                      create_role_new_num, create_role_new_arr, retention_num, pay_total_unit_arr,
                                      pay_total_num,
                                      pay_total_money, pay_total_e, pay_total_coupon, pay_total_rmb, pay_new_unit_arr,
                                      pay_new_unit_num, pay_new_num, pay_new_money, ext_boot_num, ext_boot_pc_num,
                                      ext_install_num, ext_uninstall_num, top_online_cnts, roll_login_cnts, new_cnts,
                                      ret_cnts,
                                      ret_rate, pay_users, pay_money, pay_rate, total_money, week_new_cnts,
                                      week_ret_cnts,
                                      week_ret_rate,
                                      week_pay_users, week_pay_money, week_pay_rate, week_total_money)
    select timeline_date,
    dim_type,
    business,
    pid,
    game_code,
    is_a,
    game_server,
    sum(view),
    sum(click),
    uniqExactArray(reg_arr),
    uniqExactArray(login_new_arr),
    uniqExactArray(new_arr),
    groupUniqArrayArray(new_arr),
    groupUniqArrayArray(active_arr),
    uniqExactArray(valid_new_arr),
    groupUniqArrayArray(create_role_arr),
    uniqExactArray(create_role_new_arr),
    groupUniqArrayArray(create_role_new_arr),
    uniqExactArray(retention_arr),
    groupUniqArrayArray(pay_total_unit_arr),
    sum(pay_total_num),
    sum(pay_total_money),
    sum(pay_total_e),
    sum(pay_total_coupon),
    sum(pay_total_rmb),
    groupUniqArrayArray(pay_new_unit_arr),
    uniqExactArray(pay_new_unit_arr),
    sum(pay_new_num),
    sum(pay_new_money),
    sum(ext_boot_num),
    sum(ext_boot_pc_num),
    sum(ext_install_num),
    sum(ext_uninstall_num),
    max(top_online_cnts),
    groupUniqArrayArray(roll_login_cnts),
    sum(new_cnts),
    groupArrayArray(ret_cnts),
    groupArrayArray(ret_rate),
    groupArrayArray(pay_users),
    groupArrayArray(pay_money),
    groupArrayArray(pay_rate),
    groupArrayArray(total_money),
    sum(week_new_cnts),
    groupArrayArray(week_ret_cnts),
    groupArrayArray(week_ret_rate),
    groupArrayArray(week_pay_users),
    groupArrayArray(week_pay_money),
    groupArrayArray(week_pay_rate),
    groupArrayArray(week_total_money)
    from bi_gameop.gameop_wide_dw
    where timeline_date = '#(timeline_date)'
    group by timeline_date, dim_type, business, pid, game_code, is_a, game_server