---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: bi
  name: bi-data-management-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: cephfs-storageclass
  ~