#配置生效的配置
server:
  port: 18882
  servlet:
    context-path: /ey

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always

#设置日志配置文件
logging:
  config: classpath:logback-spring.xml