server:
  port: 18889
  servlet:
    context-path: /gameop

#配置生效的配置
spring:
  profiles:
    include:
    - swagger
  http:
    multipart:
      max-file-size: 10Mb
      max-request-size: 10Mb

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always

logging:
  config: classpath:logback-spring.xml