create database bi_dashboard ON CLUSTER cluster_1shards_2replicas;

CREATE TABLE bi_dashboard.st_game_operate_kpi_statistic ON CLUSTER cluster_1shards_2replicas (
 `id` UInt32 COMMENT '主键',
 `group_name` String COMMENT '部门',
 `kpi_category` String COMMENT '考核分类',
 `category1` String COMMENT '一级业务类别',
 `category2` String COMMENT '二级业务类别',
 `category3` String COMMENT '三级业务类别',
 `kpi_year` String COMMENT '考核年',
 `start_time` Date COMMENT '考核开始时间',
 `end_time` Date COMMENT '考核结束时间',
 `kpi_name` String COMMENT 'KPI指标',
 `kpi_value` Float32 COMMENT 'KPI值'
) ENGINE = ReplicatedMergeTree('/clickhouse/tables/cluster_1shards_2replicas/{layer}-{shard02}/bi_dashboard/st_game_operate_kpi_statistic', '{replica}') ORDER BY id;

CREATE TABLE bi_dashboard.st_game_operate_roi_statistic ON CLUSTER cluster_1shards_2replicas (
 `date_time` Date COMMENT '时间',
 `kpi_id` UInt32 COMMENT '关联st_game_operate_kpi_statistic.id',
 `group_name` String COMMENT '部门',
 `category1` String COMMENT '一级业务类别',
 `category2` String COMMENT '二级业务类别',
 `category3` String COMMENT '三级业务类别',
 `kpi_target` Float32 COMMENT 'KPI值',
 `agent_id` String COMMENT '媒体商',
 `channel_id` String COMMENT '子渠道',
 `game_category` UInt8 COMMENT '游戏类型',
 `game_category_name` String COMMENT '游戏类型名称',
 `game_code` String COMMENT '游戏code',
 `game_name` String COMMENT '游戏名称',
 `real_income` Float32 COMMENT '实际收入',
 `real_cost` Float32 COMMENT '实际成本',
 `real_roi` Float32 COMMENT '实际ROI',
 `estimate_income` Float32 COMMENT '预估收入',
 `estimate_cost` Float32 COMMENT '预估成本',
 `estimate_roi` Float32 COMMENT '预估ROI',
 `timeline` String  COMMENT '分区字段'
) ENGINE = ReplicatedMergeTree('/clickhouse/tables/cluster_1shards_2replicas/{layer}-{shard02}/bi_dashboard/st_game_operate_roi_statistic', '{replica}')
PARTITION BY timeline ORDER BY (date_time,kpi_id,group_name,category1,category2,category3,kpi_target,agent_id,channel_id,game_code,game_name);

CREATE TABLE bi_dashboard.st_game_operate_channel_statistic ON CLUSTER cluster_1shards_2replicas (
 `agg_dim` String COMMENT '聚合粒度',
 `date_time` Date COMMENT '时间',
 `user_type` String COMMENT '用户类型（推广用户/自然用户）',
 `user_environment` String COMMENT '用户环境（渠道部网吧、外部网吧和外部非网吧）',
 `agent_id` String COMMENT '媒体商',
 `channel_type` String COMMENT '渠道类型',
 `channel_id` String COMMENT '子渠道',
 `cid_id` String COMMENT '活动策略',
 `billing_type` String COMMENT '计费方式',
 `position` String COMMENT '推广位',
 `game_category` UInt8 COMMENT '游戏类型',
 `game_category_name` String COMMENT '游戏类型名称',
 `game_code` String COMMENT '游戏code',
 `game_name` String COMMENT '游戏名称',
 `reg_cnts` UInt32 COMMENT '注册',
 `reg_array` Array(String) COMMENT '注册明细',
 `active_cnts` UInt32 COMMENT '活跃',
 `active_array` Array(String) COMMENT '活跃明细',
 `pay_users` UInt32 COMMENT '付费用户数',
 `pay_array` Array(String) COMMENT '付费用户明细',
 `pay_cnts` UInt32 COMMENT '付费次数',
 `pay_money` Float32 COMMENT '付费金额',
 `arpu` Float32 COMMENT 'ARPU（活跃）',
 `arppu` Float32 COMMENT 'ARPPU（付费）',
 `estimate_income` Float32 COMMENT '预估收入',
 `estimate_cost` Float32 COMMENT '预估成本',
 `estimate_cp_cost` Float32 COMMENT '预估CP成本',
 `estimate_channel_cost` Float32 COMMENT '预估渠道成本',
 `estimate_roi` Float32 COMMENT '预估ROI',
 `estimate_profit` Float32 COMMENT '预估利润',
 `estimate_arpu` Float32 COMMENT '预估ARPU',
 `estimate_arppu` Float32 COMMENT '预估ARPPU',
 `real_income` Float32 COMMENT '实际收入',
 `real_cost` Float32 COMMENT '实际成本',
 `real_roi` Float32 COMMENT '实际ROI',
 `real_profit` Float32 COMMENT '实际利润',
 `start_pc` UInt32 COMMENT '启动PC',
 `valid_pc` UInt32 COMMENT '生效pc',
 `score` UInt32 COMMENT '综合评分',
 `timeline` String  COMMENT '分区字段'
) ENGINE = ReplicatedMergeTree('/clickhouse/tables/cluster_1shards_2replicas/{layer}-{shard02}/bi_dashboard/st_game_operate_channel_statistic', '{replica}')
PARTITION BY timeline ORDER BY (agg_dim, date_time, user_type, user_environment, agent_id, channel_type, channel_id, cid_id, billing_type, position, game_category, game_category_name, game_code, game_name);


CREATE TABLE bi_dashboard.st_game_operate_pruduct_quality_statistic ON CLUSTER cluster_1shards_2replicas (
 `agg_dim` String COMMENT '聚合粒度',
 `date_time` Date COMMENT '时间',
 `customer_id` UInt32 COMMENT '合作方ID',
 `customer_name` String COMMENT '合作方名称',
 `cooperate_type` String COMMENT '合作方式',
 `game_category` UInt8 COMMENT '游戏类型',
 `game_category_name` String COMMENT '游戏类型名称',
 `game_code` String COMMENT '游戏code',
 `game_name` String COMMENT '游戏名称',
 `agent_id` String COMMENT '媒体商',
 `channel_type` String COMMENT '渠道类型',
 `channel_id` String COMMENT '子渠道',
 `reg_cnts` UInt32 COMMENT '注册',
 `reg_array` Array(String) COMMENT '注册明细',
 `active_cnts` UInt32 COMMENT '活跃',
 `active_array` Array(String) COMMENT '活跃明细',
 `pay_users` UInt32 COMMENT '付费用户数',
 `pay_array` Array(String) COMMENT '付费用户明细',
 `pay_cnts` UInt32 COMMENT '付费次数',
 `pay_money` Float32 COMMENT '付费金额',
 `arpu` Float32 COMMENT 'ARPU（活跃）',
 `arppu` Float32 COMMENT 'ARPPU（付费）',
 `estimate_income` Float32 COMMENT '预估收入',
 `estimate_cost` Float32 COMMENT '预估成本',
 `estimate_cp_cost` Float32 COMMENT '预估CP成本',
 `estimate_channel_cost` Float32 COMMENT '预估渠道成本',
 `estimate_roi` Float32 COMMENT '预估ROI',
 `estimate_arpu` Float32 COMMENT '预估ARPU',
 `estimate_arppu` Float32 COMMENT '预估ARPPU',
 `real_income` Float32 COMMENT '实际收入',
 `real_cost` Float32 COMMENT '实际成本',
 `real_cp_cost` Float32 COMMENT '实际CP成本',
 `real_channel_cost` Float32 COMMENT '实际渠道成本',
 `real_roi` Float32 COMMENT '实际ROI',
 `timeline` String  COMMENT '分区字段'
) ENGINE = ReplicatedMergeTree('/clickhouse/tables/cluster_1shards_2replicas/{layer}-{shard02}/bi_dashboard/st_game_operate_pruduct_quality_statistic', '{replica}')
PARTITION BY timeline ORDER BY (agg_dim, date_time, customer_id, customer_name, cooperate_type, game_category, game_category_name, game_code, game_name, agent_id, channel_type, channel_id);